language: node_js

node_js:
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: M8QqctYIGRE1xyEpOP+hfMXl9cX7qutCrteX6fAGKiIrDuHFcviiSEeKwxDZpBCSolfvzowzc2m58bKzh15kYmjRS7E/AGtjLoqXgskIz0y4t+JNGV4nVOQoBNHT/BvUo5SrfW1QXwEv0wI52YQDUxbttOOnU0yIrflwYK4wRa4=
  app: openroulette
  on:
    repo: Wildhoney/Openroulette
